header_pages: ['']
title: SalmonLisp
author:
  name: Kai Daniel Gonzalez
  email: gkai70264@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  SalmonLisp is awesome.
theme: tactile